<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Prism.DryIoc" Version="8.1.97" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.0" />
    <PackageReference Include="Syncfusion.SfSkinManager.WPF" Version="32.1.19" />
    <PackageReference Include="Syncfusion.Shared.WPF" Version="32.1.19" />
    <PackageReference Include="Syncfusion.Tools.WPF" Version="32.1.19" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Modules\SepalWRFM.Modules.ModuleName\SepalWRFM.Modules.Landing.csproj" />
    <ProjectReference Include="..\Modules\SepalWRFM.Modules.WRFM\SepalWRFM.Modules.WRFM.csproj" />
    <ProjectReference Include="..\..\SepalWRFM.Modules.ProductionSurveilance\SepalWRFM.Modules.ProductionSurveilance.csproj" />
    <ProjectReference Include="..\SepalWRFM.Core\SepalWRFM.Core.csproj" />
    <ProjectReference Include="..\Services\SepalWRFM.Services.Interfaces\SepalWRFM.Services.Interfaces.csproj" />
    <ProjectReference Include="..\Services\SepalWRFM.Services\SepalWRFM.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\IconResources.xaml" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\**\*.png" />
  </ItemGroup>
</Project>